name: Martygsensations.com
favicon: null
layout_spectrum: 0.6351252410095185
typography_spectrum: 0.6155451114755124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bfc1c0'
    - '#f0efeb'
    - '#9d6b30'
    - '#282826'
    - '#565c68'
  brandStrength: 0.9313014601357281
  lightness: 0.6278143641538918
  saturation: 0.18826276436448097
  rhythmicContrast: 0.024918282870203257
purpose: []
